### ISSUE TITLE
Problem with pip - 'latest' and parse from freeze options

### ISSUE THREAD

**Issue by marcinbojko** [voxpupuli/puppet-python#356]
1. Simple configuration:
```yaml
python:
    dev: latest
    pip: latest
    python_pips:
      erl_terms:
        ensure: 0.1.1
        pkgname: erl_terms
      psutil:
        pkgname: psutil
```

CentOS 7.2/7.3

Using pip 'latest' doesn't work. Pip stays at 8.1.2.

2. Parse unless with pip freeze

In your 'unless' statement, exemplary phrase:
`pip freeze | grep -i -e ^erl_terms==0.1.1$ || pip list | sed -e 's/[ ]\+/==/' -e 's/[()]//g' | grep -i -e ^erl_terms==0.1.1
`
will always return notify due to:

> You are using pip version 8.1.2, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> You are using pip version 8.1.2, however version 9.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.

After manual upgrade pip to 9.0.1, notify changes to:

`DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.`
This still generates notify event and installs pips on every puppet run.
