### ISSUE TITLE
Unknown function 'fact' python/manifests/install.pp, line: 269

### ISSUE THREAD

**Issue by n1md4** [voxpupuli/puppet-python#570]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.17.0
- Ruby: 2.5.5
- Distribution: centos
- Module version: 4.1.1

## How to reproduce (e.g Puppet code you use)

from the example code:

```yaml
python::python_pyvenvs:
  "/opt/env1":
    version: "system"
  "/opt/env2":
    version: "system"
python::python_pips:
  "nose":
    virtualenv: "/opt/env1"
  "coverage":
    virtualenv: "/opt/env2"
```

## What are you seeing

Error: Unknown function: 'fact'.

## What behaviour did you expect instead

Puppet run to complete and create virtualenv appropriately.

## Output log

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'fact'. ( .... python/manifests/install.pp, line: 269, column: 14) on node xxxx

Log to entirely verbatim.

## Any additional information you'd like to impart

This is the line of code it fails on:

if fact('lsbdistcodename') == 'trusty' {
