### ISSUE TITLE
Support puppet-epel 5.0.0 dependency

### ISSUE THREAD

**Issue by rridge532** [voxpupuli/puppet-python#671]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.x+
- Ruby: N/A
- Distribution: N/A
- Module version: puppet-python 7.0.0, epel 5.0.0

## How to reproduce (e.g Puppet code you use)
```
fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.6.0"
    python:
      repo: "puppet/python"
      ref: "7.0.0"
    epel:
      repo: "puppet/epel"
      ref: "5.0.0"
```

## What are you seeing
puppet-python currently only supports puppet-epel <5.0.0 but [epel was updated](https://forge.puppet.com/modules/puppet/epel/changelog) to version 5.0.0 recently.

## What behaviour did you expect instead
Support puppet-epel <6.0.0

## Any additional information you'd like to impart
This versions only breaking change appears to be dropping support for Puppet 6 which was already dropped in puppet-python with 7.0.0 so should be fairly easy
